### ISSUE TITLE
Export excel when the return garbled

### ISSUE THREAD

**Issue by jiusazai** [wuwz/ExcelKit#1]
PK�twJdocProps/core.xml��]K�0���+B�ۤ
l�Q����û��b�A���fݬ(^zy�>����Ԉ�����
���4���
?6��o�$)�q�sƂx[�W��rB��A	��X���8%B]G����RP�"
�hE�hK���'��ߕ�\��͍���FP��'y��o6�S��,��5MS6����dw�0/���%�:A�<۹t �(:x��P��]]7[\4_���k芳5/�sI~����h\}�������9)�ϯ��OPKZ�8��PK�twJ_rels/.rels���N�0��}�(��ݐBMwAH�Mh<@H�6jG���	Cv����O����g�);
J��F
�������Ս�vU�>ହd��b�)d%G�x�͈^�"���S��3
���i�kH_���8���U2��Z��k�K���������?L��(d�d%�^(MODS]���l�S�`Ѯb*���O'Kf_�t�H]].u~���լ�P�ߕ�N-�\CW�PKW(^#�FPK�twJ[Content_Types].xml���N�0E��
�[�e�J��%T�|��'�U�d���{&)�%Z��ʲ��{nFq5Y[CV����c6���J�yM�fw�%�4EQ�6A�K5�rW�'ف��'��Vd��9B.���ht��w\.s�A����Z�4�ܮq�eG0��뭶��T�`��|��7P�a�4��!����}�~���a}��D��LE��¢�+/�ч����Pַ���K�}'�	1k��� ^���ջ���
O���s�_"���S� T��5�K�U����;���_|\<{�8�
�dVhw\�A��p�O��=W��ûo�WPK%��8(PK�twJdocProps/app.xmlM��
�0D�~EȽ��ADҔ���A? ��6�lB�J?ߜ���0���ͯ�)�@��׍H6���V>��$;�SC
;̢(�ra�g�l�&�e��L!y�%��49��`_���4G���F��J��Wg
�GS�b����
~�PK�|wؑ�PK�twJxl/sharedStrings.xmlm�K�&�q��^E��V�>�����W`/����UU�o�੡��ࡖၗ��6��<*�F���f&<q��������迼}����w�7���e=�����w��������o?�݇��o?쯿~���;���_�|�ï��������w?}���?�������7_�/�ܯ�|����_~����_|���ܿ}��{I���<?}y���ۧ��}��������_��������}���������g�r�yY����E굤vV�־�a��������x6�'�Zf.���r|�6M��{�~|t����֤���W;+�]�f;���ǧ�#��<����[��Qo�]��֗�h�g����=��Vc�s�h�ꗳ�����m����g��̽>ӗ�oY�����ɏ����;��͵�poYj�n��a|��z�]�����O=k�v/i�����r�_gg�ߡ����u֚f�����_�|��N�c�Y��u��w���l�=\o��i�g�]�0������X6v����y��;���b��V���ъ�қ�vS\��ە6ҕ�
���ܲi+#��_�9Y�Eg����I3;:WO9��T���fj\��
f8wK��䀿�2��g����ϥg�Dk��k��]�,C5ܿ?Mk�w�0���v9���t�����Y���⧯��A��p��Z؟RY�jC�Y[)�_�y\ݛ��w쏲��Hŋ�P��'�V�N�9������LГ�9o��p����D|�R�z�7�M�>`�����졿\,;=\&I7�o�&�k�}�<3\OۗnHC�v��vH%W=�F�3�O����Hg��A�HH��NQ�����G*
�~��+����}����!f�g��Mx�(lLN����4X~�V
���4ݭ����7��V�5��t����;A�b�X�P���=��]�=C��C�<��Q@�-��ߓ���-�y��3UV�51G�.�A�nڶ��?N��|�r[��:sґ�&NG�?W/���R�W�k�
"����;����ce����n9.=��KK!�X��#b��v���<��'De�bq�a��ti3Y9��#�ץ��(������4�T"��W&�_f�b���n��ȣ�ng�p���J!�	ǆ�)XC�=�B����*�P,�
�p�n;W��a��[�?i#�A_�{��S�K	�C9S�S*�@F�������*��U�~��}��� ��?\e>w�Ec�0,A�<�h��q}�vP����
��s��l��=���Q7��	�����	��S>��3�������$G��6eء������$���&�����������7E�>M�s]0{X�i8H��k����c���/���hѾ�����Q?�ݏukk�==��V��
kE�0�ig[%���(��
ֻ��)(��~XXb�'џ��uQ�K�7�۶�ZL��i4*st�����~�>��ы���~�<j�����֧�eT\߱��qi����Rsy$P�3d���n��0��`AW� ^:̏��B������o$7��-�|֋��chM���|v 7����|�o�ۗٚ���v��0�5r=2�]���N��Y��Z��~x9m6a
�6�6�镫��7��nmc�t�~=ּ�R��R��y@���T��̣��#>�_�������u�%���,�'�
���|@�v�|��&
�_����l+�/��NSZ��z5ԇ{fٺ��Ɵ�޻��:>����H�3^�<����;�G%wʭ=���G2����ЂH@<����W�:.�~�^;�m�m~����	�ϟ�I�'��w�?�g�k����������Zk���?��t�}�+��I�6���#O��'��(l��@�B_�a�/��NZk?NA��r)�u	!&����ƿ�L�%�ϙ��R;!����u��~�?ע�E��q��r��Y_O�4�������c���[��9Iɘ�Jz�[p�
E���X���u�x~DfW��^5��ѿJ��u2\�}O�>�/5����Y�NLd�����sJ"yM�"���aO�a��ȴ����MaN����B���޷bj����9%6��|s�Ŏ�UQ��x>��7������)g��6�؁!!�P����u	�1P1?n�M�>�]g<?���H���+�ʝ�Wz����|�
&�6n�����X$�|m�x>p�<�(���-�m�
�YI��kЇ�I��A���rO�q�b~n��s�������\��:��9�7h�<�'������"��p��(����O����?�Q�ý�G|�F*:���Əx��*G_/"L���`ަ���ҩ'�7ց)6L<՘��-%ك�H����|N3D���fVB'������Pr^�O�W͈v{��q����	��_t}�ؓ|u[<������d�k3�'��6c�6$�pH�d��1�>J��/�*�w���l1�T0Xp�a��%���=��=O2�g��^��'��_���_U��@�0 &'���Cg���35�ڰIǴƪ@!��=��G�����}\�L��4���>�nCVQ�n�w�g5\���=��
L&��O)���0�r�����k�`�ڈ�U���8�r%<P�q��ݱ�6�M�$FG���x�&{��$�Ğ<{�'���L�T˭$�[<?�<��ثm9����ߘ����Q�����!L���3�����?�9>�B9N��8?9yЗ4,����\J{�'h�_������M0H�O6��\ǻ�b}.��9��Oo�:#Cp���1����,v�F"�����.�̓ʇ��5{�ξ��D�_����i����h1�k����|2�s��3��y���Ȋ�ig�����m�Hɵae����b�.RN���E4��hԿ�[����P��y<cA�"�w
�7!V�9�'BU����(~C��
zyޣ��nn^_�R|�E�����a�g�_�+����0t|?c��W��4�s<��#��3����ғ�W���h���������iqp��������dzǊ��h49׃��~�;�9纹@!�����L���'��-YZ�(Q"�C�o�j���c
i~Z���Y��i���K�E�x~�h{�+�M������a��u-y|��2���W<��Fz |��9�[���7& �oƹܕ�%D?9��4G�O��b��ˡ�g�����7�V7�8ꁟO�v�� �;�v	�]L1_��	_9��WӘ�C�����RX?�.DC
9i��/�[�oI*2�G.Ù9�=�x~���?����0���!g䧳O~>��E��]ҭ�u*D�� �^��-��j�~��;Q������b��v{����>�,�[�E>yΦehI���_��,	�3~?R����˖w�>a6?�T�w�n�?���I��X���H�ϋ#:����}�hdo�kҟe��'�8�] M�F~K�/a��N���-���*�?�z�p2�{��������#/6_<�T��`�3A2ꛙ��|@C8E�c>>"�4͉�󕕑��X-!�d�Fy��z�O�ۙ'��q���~Ƥ�a`��5�dEj+S�	���Q{(*�AR��}W&:�ťGj���}8��$��G=�q���"�iM�ŰPMǈ����6�������1M��)�"��u�5�D�
�O�Ϩ�0%C�?D��ߟ
B��+0�������޿�}��PK��I���)PK�twJ
xl/styles.xml�TMo� ��W �	��$M#ۑi���J��ۨ�X�Fv~}��#�$m����ｙ�e���h�$�W`K�<_P"m
Bٶ���g����T�0j��I
�/iBØ�;i�?�^Z�Ҁ3<�ֵ��Nr��h�Z,����Ҫ�[�6���6�tAYU4`�Ȋf�*�3y�+��!�
�(+� EI�#f���uϵ�8���Qz��*�҉g�A���ߓ>�.N���%-ݔֻV�h���!Hg׸!S�8�����6��[p����[
����B�����z�J��d��Yn� SZ�7����&/�U��M@�Sm�}�!��@(ނ�:&��T�^SIC���'پd}�0W��]��%�RL�r-�~���x�CC��&� �q�!��f�����n���v�W�dhv����{���b�&����hxn+'�.q��5�bP8�Zk�
����S�F�fR�C35��e�9]�PK��9
��PK�twJxl/workbook.xml���N�0�w�º��� ��!uc(�}i��v�3-+b��<^'U�����}�ݯ�?��m1�
^B1���`�_K�]^_��>�v!nV!lX�=IhS�K�I���B�>o��J9�5�>�2�"&��!ιS���P��8B�X�WA�;�� �ة��Rk{����MdF%,.ř�Fu���j��Y��/8D�t�[\��1p�8v�&�ʡ����ϧ������X,����H-r,F�ţw�7PK�5��cPK�twJxl/_rels/workbook.xml.rels���N�0@����w�v�BMwAH���Q�6��$�
�����;Y��痤ٜ�I�"�����@ap��`�y�xs��(�'���3���*6�Eҽ��<Ζ˘0�Ni��St��`ԫ���tɀ�Pj�U��m�����?����Ç�^f����v;�|!�`K��E��Tп����#�	/E>�?��48F:�G�o����{�P�4z��m�PK��X��0PK�twJxl/worksheets/sheet1.xmlu�MO[Y���|
���깯#��Ҩ5�i4�k'8�0���?�ؤ�S�M-��p���p�������>?��n��������j��iw��r��Ͽ�a^�x���o��/�����:�9ܬ���?_]>=l�7������3�w����tsux�o7wo=?]��ƫ���������y�r~��~��f��W��o����v��W������r�񷻛���;n>�k���tܞn�_�磯�p��o_�?�����͗��?w���}�8���pz���>�o���O~�z�����ǻ��͚݇�2�Ӱ^}�r8����3���~o����qs{��}[��wr����g�:=�a�:|�߯������?�՗Cx9��r^���eq�b����,�eq��x�,dq����x��������I��/�/�gY<��x�,^d���bt�M'˗�\RBÄ�ha!CI��Ж1�jBs"�D
-���)4*BU��Юa��B�"�E�����-/5/B_��ԾLߦ�}�}����}���l}�}�����e��֗ڗ�/[_j_��l}�}�����e�[�oi_�������зZ�Ҿ�~ˏb�[�o��e?�C�j}K�V�[�oi�
}��-�[�o���}+��ַ�o��}��k�
}�ַ׾}�۷����C߾���o�~��o[�ۇ�}���o�зo}{�ۇ�}��k�>��[�^���o���ڷ}��wо}�;����Bߡ������}��wh}�;��)9�ҾC�;����T��C�;h�!�Z�A������w}��wԾC�;����C߱�������}��wl}G�;��c�;j�1�2�9��C߱���9�[�Q��������w}��wҾc�;�����Bߩ�����N��}��wj}'�;��S�;i�)��Z�I�N�U��,ҾS�;����4
}��wҾS�;�����B߹�����έ�}��wn}g�;��s�;k�9��[�Y�Ρ�����w}��w־sz�+�|���έ�l�~Cߥ�]���.��}��wi}����K�h�%�]Z�E�.����.�w	}��wѾK軴���]Bߥ�]��lCpC�.�7�78�ptB�GB�N��3��st�IG�����;���pGg��%��D<:#�.�G'�љzt�=:q���K��	}tf]���e�u��t��Տĥ��;�J���ܹ"t�t9uE�R�r�ܥ����K���+�����Wt/�/��D_���W�/��	�@N���`�+g�/�0$	�P�0�a0C�0��D�� &C1$���Ő`"c0C�1��t�� >2$!��Ȑ��d(g�T_�&eHT�2�!i��`^�f1����A��fHlq3�!���`v��g=����A
&hH��^�qX��hFC��9R}�4�!Y�`���iO����AH
fjH�Q5�!��`��Dk[����Ax
�kH�6�!��e��A�
�_�J���`ֆ�mm�q��A�
&nH�17�!���`�oy����A�
�oH��7�!	��`��p�*��O�8�~�3���a��A8�qH 9�!��`*��r�����AhfsH8�9�!��`B�Dt��!��a���V?AD�0���T_��uH\�:�!���`f��v�����A�&wHt�;�!���`~�x����A�xH��Y��~�<�a�Y�T_4�yH�=��!���`���zփ��AdF{H��=��!���`��$|��A��|H·E]�~�>v:���.i�E���ϻ���>��1Y��h��d}�Y��Q��f}L�G�>��1Y��h��d}�Y��Q��f}L�G�>��1Y��NV?Y��xJ���h��d}�Y��Q��f}L�G�>��1Y��h��d}�Y��Q��f}�cn:�f��8馣n>떇�t����y7x���[��3o>���t�������N���[�}��7�~��o:��pqNG�|.Y���cp��(�G�>&�X�����b}4�c�>���|�1��Y��Q��f}L�G�>��1Y��h��d}�Y��Q��f}L�G�>��1Y��h��d}�Y����yW����b}�}�5��Y��Q��f}L�G�>��1Y��h��d}�Y��Q��f}L�G�>��1Y��h��d}�Y��qЁg����b}|�9��Y��Q��f}L�G�>��1Y��h��d}�Y��Q��f}L�G�>��1Y��h��d}�Y��qԉw����b}}�=��Y��Q��f}L�G�>��1Y��h��d}�Y��Q��f}L�G�>��1Y��h��d}�Y��q�-V?Y��8���T_��f}L�G�>��1Y��h��d}�Y��Q��f}L�G�>��1Y��h��d}�Y��Q��f}L��Y��X�d}����^R}�>��1Y��h��d}�Y��Q��f}L�G�>��1Y��h��d}�Y��Q��f}L�G�>��1Y��d���U���|�S��$�W��}J����ʬ����X_��U���+��J�Wb}e�W��J����*Y_���Y_%�+��2�d}%�Wf}�����ʬ���t��O�Wb}������Y_%�+��2�d}%�Wf}�����ʬ����X_��U���+��J�Wb}e�W��J����*Y_���Y_%�+��G���������1��+��J�Wb}e�W��J����*Y_���Y_%�+��2�d}%�Wf}7��W���{^uӫ�z���]ɛ�n����_����q�|��>�O�?�v���|�T�a����x�~>��Z����_�������c�o�py����PK�n!rBPK�twJZ�8��docProps/core.xmlPK�twJW(^#�FC_rels/.relsPK�twJ%��8(_[Content_Types].xmlPK�twJ�|wؑ��docProps/app.xmlPK�twJ��I���)�xl/sharedStrings.xmlPK�twJ��9
��
�xl/styles.xmlPK�twJ�5��c�xl/workbook.xmlPK�twJ��X��0�xl/_rels/workbook.xml.relsPK�twJ�n!rB�xl/worksheets/sheet1.xmlPK		?[#

**Comment by wuwz** [comment]
What is the development environment? Win? Mac or Linux?
Is the workspace encoding UTF-8?

**Comment by jiusazai** [comment]
I use Mac ,thanks.And I solve this problem,in the pom.xml need to add a dependency:<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>3.10.1</version>
			<scope>compile</scope>
</dependency>
If not,it will cause the problem like:
java.lang.NoClassDefFoundError: org/openxmlformats/schemas/spreadsheetml/x2006/main/CTSheet

**Comment by wuwz** [comment]
Thank you, because I do not have a Mac device, so do not notice this issue, thank you for your support, the next version will fix this problem.
