### ISSUE TITLE
导出的excel格式需要修复，原有格式无效

### ISSUE THREAD

**Issue by caydenprivate** [wuwz/ExcelKit#10]
![错误提示](http://wx2.sinaimg.cn/mw690/895dd481ly1fna5w0cj8pj20iw0b4mxn.jpg)

**Comment by caydenprivate** [comment]
数量条数较多，测试了3000条以上，才会出现这个问题

**Comment by wuwz** [comment]
重新拉取代码, 在最新的版本(2.0.5)中解决了这个问题
