### ISSUE TITLE
BUG:Excel export 时当某列数据为空时，默认把后面的数据填充到了前面，导致下标减少。

### ISSUE THREAD

**Issue by shuanger051** [wuwz/ExcelKit#3]
例如：
一列数据为：A、A、A、空、A，其实下标是4，而不是下标是3，但是程序导出时会把最后一个数据，放到了前面那个空的位置上。

**Comment by wuwz** [comment]
已修复。

**Comment by shuanger051** [comment]
HI，Man ，导入也有这个问题，我试图修改你的源码，但是发现底层的POI改起来比较麻烦。所以没改，请问这个问题也一并修复掉了吗？
