### ISSUE TITLE
导入文件占用问题

### ISSUE THREAD

**Issue by asdon** [wuwz/ExcelKit#4]
您好，我是用您在maven上的2.0的版本，但是，我导入文件后，使用excelKit读取了文件后，将文件删除的时候发现文件一直被占用，无法删除，这将会导致服务器资源冗余，如果读取文件不释放也会导致服务器内存被占用；希望您能及时修改这个问题。

**Comment by wuwz** [comment]
你好，此问题已修复，更新版本号为 2.0.2即可修复，谢谢！
